apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: gitlab-runner
  namespace: gitlab
  valuesFile: values.yaml
  releaseName: runner
  version: 0.67.0
  repo: https://charts.gitlab.io
